import Head from "next/head";
import Link from "next/link";

import classes from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="bg-red-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={classes.container}>
        <div className={classes.home_message}>
          <p className={classes.home_title}>
            このアプリは、keita
            namazueによって作られた10年後のラーメン業界の世界である。
          </p>

          <div className={classes.setting}>
            <h3>使い方は簡単</h3>
            <ul>
              <li className={classes.setting_list}>
                月に1万円払えばラーメン食べ放題
              </li>
              <li className={classes.setting_list}>アプリ決済も可能</li>
              <li className={classes.setting_list}>ラーメン情報を共有</li>
            </ul>
          </div>
        </div>

        <Link href="/ramenList">
          <a className={classes.btn}>はじめる</a>
        </Link>
        <Link href="#">
          <a className={classes.rules_btn}>利用規約を読む</a>
        </Link>
        <Link href="#">
          <a className={classes.rules_btn}>プライバシポリシー</a>
        </Link>
      </div>
    </div>
  );
}
