import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Links } from "../components/Links";
import { Nav } from "../components/Nav";
import classes from "../styles/Home.module.css";



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Links/>

      <Nav />
    </div>
  );
}
