import Head from "next/head";
import RamenDiningIcon from "@mui/icons-material/RamenDining";

import { Links } from "../components/Links";
import { Nav } from "../components/Nav";
import classes from "../styles/ramenList.module.css";

export default function ramenList() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={classes.title}>
        <h2>ラーメン店一覧</h2>
        <RamenDiningIcon />
      </div>

      <Links />

      <Nav />
    </div>
  );
}
